name = "MDBM"
uuid = "dd61e66b-39ce-57b0-8813-509f78be4b4d"
version = "0.2.2"
authors = ["Daniel Bachrathy"]

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
FunctionWrappers = "1.1.3"
PrecompileTools = "1.2.1"
StaticArrays = "0.12, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
